"""Initial migration

Revision ID: 75983bf37f41
Revises: 
Create Date: 2025-10-06 19:11:14.712838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75983bf37f41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop example table if it exists (old test table)
    try:
        op.drop_table('example')
    except:
        pass  # Table doesn't exist, that's fine
    
    op.add_column('monitored_graphics', sa.Column('in_effect_date', sa.DateTime(), nullable=True))
    op.add_column('monitored_graphics', sa.Column('reminder_scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('monitored_graphics', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('monitored_graphics', sa.Column('reminder_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_graphics', 'reminder_message_id')
    op.drop_column('monitored_graphics', 'reminder_sent')
    op.drop_column('monitored_graphics', 'reminder_scheduled_time')
    op.drop_column('monitored_graphics', 'in_effect_date')
    # ### end Alembic commands ###
